server:
  port: 8000
  env: development

jwt:
  expiration: 3600

database:
  host: localhost
  port: 5432
  user: zpay
  password: zpay
  dbname: zpay
  sslmode: disable
  maxconns: 25

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0