global:
  scrape_interval: 50s
  evaluation_interval: 50s

scrape_configs:
  - job_name: zpay-backend
    static_configs:
      - targets:
          - host.docker.internal:8000
        labels:
          service: zpay-backend
          env: local